name: EAS Build

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Build on EAS
      run: eas build --platform ios --non-interactive --no-wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}